Public Class frmTimetable
    Private Sub frmTimetable_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Label2.Text = "Date: " + String.Format("{0:dd/MM/yyyy}", DateTime.Now)
        Label3.Text = "Time: " + Now.ToShortTimeString
    End Sub

    Private Sub btnReturn_Click(sender As Object, e As EventArgs) Handles btnReturn.Click
        Hide()
        frmHome.Show()
    End Sub

    Private Sub cbxRoom_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cbxRoom.SelectedIndexChanged
        bm9.Text = ""
        bm10.Text = ""
        bm12.Text = ""
        bm13.Text = ""
        bm14.Text = ""
        bm15.Text = ""
        bm16.Text = ""
        tb9.Text = ""
        tb10.Text = ""
        tb11.Text = ""
        tb12.Text = ""
        tb13.Text = ""
        tb14.Text = ""
        tb15.Text = ""
        tb16.Text = ""
        wb9.Text = ""
        wb10.Text = ""
        wb11.Text = ""
        wb12.Text = ""
        wb13.Text = ""
        wb14.Text = ""
        wb15.Text = ""
        wb16.Text = ""
        thb9.Text = ""
        thb10.Text = ""
        thb11.Text = ""
        thb12.Text = ""
        thb13.Text = ""
        thb14.Text = ""
        thb15.Text = ""
        thb16.Text = ""
        fb9.Text = ""
        fb10.Text = ""
        fb11.Text = ""
        fb12.Text = ""
        fb13.Text = ""
        fb14.Text = ""
        fb15.Text = ""
        fb16.Text = ""
        Select Case cbxRoom.SelectedItem
            Case "BK1.01"
                bm9.Text = "Opening"
                bm12.Text = "Security in IoT"
                bm13.Text = "Security in IoT"
                bm14.Text = "Networking"
                bm15.Text = "Networking"
                tb10.Text = "Justification of IoT"
                tb11.Text = "Networking"
                tb12.Text = "First Aid"
                tb13.Text = "Upcoming Web Tech."
                tb14.Text = "Upcoming Web Tech"
                tb15.Text = "Upcoming Web Tech"
                tb10.Text = "Justification of IoT"
                wb11.Text = "Networking"
                wb14.Text = "NoSQL Databases"
                wb15.Text = "Relational Databases"
                thb9.Text = "First Aid"
                thb12.Text = "Safety Critical"
                thb13.Text = "Safety Calm"
                thb14.Text = "Justification of IoT"
                thb15.Text = "Website Design"
                fb14.Text = "Results Celebration"
                fb15.Text = "Close"
            Case "BK1.02"
                bm9.Text = "Opening"
                wb12.Text = "Security in IoT"
                wb13.Text = "Security in IoT"
                wb14.Text = "Networking"
                wb15.Text = "Networking"
                tb10.Text = "Justification of IoT"
                tb11.Text = "Networking"
                tb12.Text = "First Aid"
                thb13.Text = "Upcoming Web Tech."
                tb14.Text = "Upcoming Web Tech"
                tb15.Text = "Upcoming Web Tech"
                thb10.Text = "Justification of IoT"
                thb11.Text = "Networking"
                thb14.Text = "NoSQL Databases"
                tb15.Text = "Relational Databases"
                fb9.Text = "First Aid"
                fb12.Text = "Safety Critical"
                fb13.Text = "Safety Calm"
                fb14.Text = "Justification of IoT"
                thb15.Text = "Website Design"
                fb12.Text = "Results Celebration"
                fb14.Text = "Close"
            Case "BK1.03"
                bm9.Text = "Opening"
                wb10.Text = "Security in IoT"
                wb13.Text = "Security in IoT"
                wb11.Text = "Networking"
                wb12.Text = "Networking"
                tb12.Text = "Justification of IoT"
                tb13.Text = "Networking"
                tb14.Text = "First Aid"
                thb10.Text = "Upcoming Web Tech."
                tb10.Text = "Upcoming Web Tech"
                tb15.Text = "Upcoming Web Tech"
                thb10.Text = "Justification of IoT"
                thb11.Text = "Networking"
                thb14.Text = "NoSQL Databases"
                tb15.Text = "Relational Databases"
                fb9.Text = "First Aid"
                fb10.Text = "Safety Critical"
                fb11.Text = "Safety Calm"
                fb12.Text = "Justification of IoT"
                thb15.Text = "Website Design"
            Case "BK1.04"
            Case "BK1.05"
        End Select
    End Sub
End Class